### ISSUE TITLE
Wallet unreachable 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#381] opened 2018-11-21 07:45 UTC
Message on Intercom: I am unable to open the wallet. It says update the app but when it is opened it goes to a blank screen. Please could you advise what I need to do to fix this . I have an iPhone 6S

**Comment by lucasvanhalst** [comment] 2018-11-21 08:44
duplicate of #379

**Closed by lucasvanhalst** 2018-11-21 08:44 UTC
Labels: priority_major
