### ISSUE TITLE
Error in ERC20 transaction

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#391] opened 2019-04-24 14:40 UTC
```
TypeError: null is not an object (evaluating 'e.transactions')
file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/main.js:1:121243
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:468561
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169786
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
notifyNext@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:398907
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:517517
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169786
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:403020
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:468659
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:376640
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
notifyNext@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:562346
_next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:517517
next@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:169458
l@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:660864
onInvokeTask@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/vendor.js:1:91857
runTask@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/polyfills.js:3:10844
invokeTask@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/polyfills.js:3:16801
p@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/polyfills.js:2:27654
v@file:///var/mobile/Containers/Data/Application/F7F6EADF-65F8-4469-A27A-F2EC3272F081/Library/Caches/embedded_apps/threefold-testnet/build/polyfills.js:2:27894
```

![2019-04-24 16 38 23](https://user-images.githubusercontent.com/17762105/56668204-6d441880-66af-11e9-9df4-1df685846ad8.jpg)
![2019-04-24 16 38 28](https://user-images.githubusercontent.com/17762105/56668202-6d441880-66af-11e9-8890-7922c7c76c97.jpg)
![2019-04-24 16 38 32](https://user-images.githubusercontent.com/17762105/56668209-6ddcaf00-66af-11e9-9595-a416767d9531.jpg)

**Comment by LeeSmet** [comment] 2019-04-24 15:14
This problem seems to be caused by a lack of funds to pay the registration fee, after aquiring enough tokens the error no longer happened

**Comment by lucasvanhalst** [comment] 2019-04-25 09:29
Fixed on staging, this was due to a change in the explorer api (http response 204 instead of 400 'unreconigzed hash')

**Closed** 2019-04-26 14:53 UTC
Labels: priority_major, type_bug
